# General
title: Chizobam Nwagwu
description: "Passionate about people-centered policy."
avatar: avatar.png
#baseurl: ""
#url: ""

# Social media

linkedin: https://www.linkedin.com/in/cnwagwu/
twitter: https://twitter.com/chizokemi
medium: https://chizobamn.medium.com/
figma: x
github: https://github.com/cnwagwu
facebook: x
instagram: x
rss: x

# Build settings
theme:
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Date/time
date: "%B %-d, %Y"
timezone: 

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "work"
    values:
      layout: "work"

# Collections
collections:
  pages:
    output: true
    permalink: :title
  posts:
    output: true
    permalink: /posts/:title
  work:
    output: true
    permalink: /work/:title

# Exclude
exclude:
  - gemfiles/
  - Gemfile
  - Gemfile.lock
